constitution = {
  legislative_branch: {
    congress: ["Senate", "House Of Representatives"],
    offices: [
      "Architect Of The Capitol", 
      "United States Botanic Garden", 
      "General Accounting Office",
      "Government Printing Office",
      "Library Of Congress",
      "Congressional Budget Office"
    ]
  },
  
  executive_branch: {
    administration: {},
    offices_of_the_president: [
      "White House Office",
      "Office Of The Vice President",
      "Council Of Economic Advisors",
      "Council On Environmental Quality",
      "National Security Council",
      "Office Of Administration",
      "Office Of Management And Budget",
      "Office Of National Drug Control Policy",
      "Office Of Policy Development",
      "Office Of Science And Technology Policy",
      "Office Of The U.S. Trade Representative",
      ],
    departments: [
      "Department Of Agriculture",
      "Department Of Commerce",
      "Department Of Defense",
      "Department Of Education",
      "Department Of Energy",
      "Department Of Health And Human Services",
      "Department Of Homeland Security",
      "Department Of Housing And Urban Development",
      "Department Of The Interior",
      "Department Of Justice",
      "Department Of Labor",
      "Department Of State",
      "Department Of Transportation",
      "Department Of The Treasury",
      "Department Of Veterans Affairs",
      ],
    i_e_g_c: [
      "African Development Foundation",
      "Central Intelligence Agency",
      "Commodity Futures Trading Commission",
      "Consumer Product Safety Commission",
      "Corporation for National and Community Service",
      "Defense Nuclear Facilities Safety Board",
      "Environmental Protection Agency",
      "Equal Employment Opportunity Commission",
      "Export-Import Bank of the United States",
      "Farm Credit Administration",
      "Federal Communications Commission ",
      "Federal Deposit Insurance Corporation",
      "Federal Election Commission",
      "Federal Emergency Management Agency",
      "Federal Housing Finance Board",
      "Federal Labor Relations Authority ",
      "Federal Maritime Commission",
      "Federal Mediation and Conciliation Service ",
      "Federal Mine Safety and Health Review Commission",
      "Federal Reserve System",
      "Federal Retirement Thrift Investment Board",
      "Federal Trade Commission",
      "General Services Administration",
      "Inter-American Foundation ",
      "Merit Systems Protection Board ",
      "National Aeronautics and Space Administration",
      "National Archives and Records Administration",
      "National Capital Planning Commission ",
      "National Credit Union Administration",
      "National Foundation on the Arts and the Humanities",
      "National Endowment for the Humanities",
      "National Endowment for the Arts ",
      "Institute of Museum and Library Services ",
      "National Gallery of Art",
      "National Labor Relations Board ",
      "National Mediation Board ",
      "National Partnership for Reinventing Government",
      "National Railroad Passenger Corporation (Amtrak)",
      "National Science Foundation",
      "National Transportation Safety Board",
      "Nuclear Regulatory Commission",
      "Occupational Safety and Health Review Commission",
      "Office of Government Ethics ",
      "Office of Personnel Management ",
      "Office of Special Counsel",
      "Panama Canal Commission",
      "Peace Corps",
      "Pension Benefit Guaranty Corporation",
      "Postal Rate Commission ",
      "Railroad Retirement Board ",
      "Securities and Exchange Commission",
      "Selective Service System",
      "Small Business Administration ",
      "Social Security Administration ",
      "Tennessee Valley Authority ",
      "Thrift Depositor Protection Oversight Board ",
      "Trade and Development Agency ",
      "United States Arms Control and Disarmament Agency",
      "United States Commission on Civil Rights",
      "United States Information Agency ",
      "United States International Development Cooperation Agency ",
      "United States International Trade Commission",
      "United States Postal Service"
    ]
  },
  
  judicial_branch: {


  }
}